spring:
  datasource:
    url: ENC(QENFw9mbKH7jOBm97RCv5zfC8FO4/Hk2YEq9DendCpsW/grR4rOAJVYaDyk7EriRqSct3NblXFo=)
    username: ENC(14WfeHUldmLYUFEDSfTwkYELrlCcKfEm)
    password: ENC(uk6pKK+N5Pz3diuWAqZGQgjiVG5gQHcO)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
    default-fetch-size: 100
    default-statement-timeout: 30
    jdbc-type-for-null: VARCHAR

newcar:
  pdf-upload-dir: ${NEWCAR_PDF_UPLOAD_DIR:./uploads/newcar-production-certificates}
mobile-ok:
  enabled: true
  key-file: ${MOBILE_OK_KEY_FILE:file:./src/main/resources/mobile-ok/mok_keyInfo_dev.dat}
  key-password: ${MOBILE_OK_KEY_PASSWORD:@dewa1004}
  client-tx-id-prefix: ${MOBILE_OK_CLIENT_TX_ID_PREFIX:Dacos309}
  site-url: ${MOBILE_OK_SITE_URL:t.dcross.kr}
  token-url: ${MOBILE_OK_TOKEN_URL:https://scert-dir.mobile-ok.com/agent/v1/token/get}
  auth-request-url: ${MOBILE_OK_AUTH_REQUEST_URL:https://scert-dir.mobile-ok.com/agent/v1/auth/request}
  confirm-url: ${MOBILE_OK_CONFIRM_URL:https://scert-dir.mobile-ok.com/agent/v1/confirm/request}

with-auth:
  enabled: ${WITHAUTH_ENABLED:true}
  issue-oauth-url: ${WITHAUTH_ISSUE_OAUTH_URL:https://t-api.withauth.co.kr/oauth/token}
  parse-token-url: ${WITHAUTH_PARSE_TOKEN_URL:https://t-api.withauth.co.kr/cert/v1.0/kcert/v1.0/parse}
  sdk-url: ${WITHAUTH_SDK_URL:https://t-api.withauth.co.kr/v1/assets/js/withauthSdk/client_init.js}
  client-id: ${WITHAUTH_CLIENT_ID:}
  client-secret: ${WITHAUTH_CLIENT_SECRET:}
  encrypt-key: ${WITHAUTH_ENCRYPT_KEY:}
  encrypt-iv: ${WITHAUTH_ENCRYPT_IV:}
