DECLARE
    PROCEDURE add_column_if_missing(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_column;
        IF v_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_column || ' ' || p_definition || ')';
        END IF;
    END;
BEGIN
    add_column_if_missing('TR_CARNO_DETACH', 'NUMPLATE_MSG_TOKEN', 'VARCHAR2(64 CHAR)');
    add_column_if_missing('TM_NUMPLATE_LIST', 'NUMPLATE_MSG_TOKEN', 'VARCHAR2(64 CHAR)');
    add_column_if_missing('TR_CARNO_DETACH', 'CONFIRM_NO', 'VARCHAR2(500 CHAR)');
END;
/

ALTER TABLE TR_CARNO_DETACH MODIFY (CONFIRM_NO VARCHAR2(500 CHAR));

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_CARNO_DETACH_NP_TOKEN';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_CARNO_DETACH_NP_TOKEN ON TR_CARNO_DETACH (NUMPLATE_MSG_TOKEN)';
    END IF;
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_NUMPLATE_LIST_MSG_TOKEN';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_NUMPLATE_LIST_MSG_TOKEN ON TM_NUMPLATE_LIST (NUMPLATE_MSG_TOKEN)';
    END IF;
END;
/
