-- 번호판 매니저 패스키 공개키 저장소. 운영 반영 전에 DACOS 스키마에서 1회 실행한다.
-- 생체정보와 개인키는 기기 밖으로 나오지 않으며 이 테이블에는 공개키만 저장된다.
CREATE TABLE TM_NUM_MANAGER_PASSKEY (
    CREDENTIAL_ID       VARCHAR2(1400) NOT NULL,
    MANAGER_TEL_HASH    VARCHAR2(64)   NOT NULL,
    USER_HANDLE         VARCHAR2(128)  NOT NULL,
    PUBLIC_KEY_COSE     VARCHAR2(4000) NOT NULL,
    SIGNATURE_COUNT     NUMBER(19)     DEFAULT 0 NOT NULL,
    TRANSPORTS          VARCHAR2(200),
    BACKUP_ELIGIBLE_YN  CHAR(1)        DEFAULT 'N' NOT NULL,
    BACKUP_STATE_YN     CHAR(1)        DEFAULT 'N' NOT NULL,
    USE_YN              CHAR(1)        DEFAULT 'Y' NOT NULL,
    INS_DATE            DATE           DEFAULT SYSDATE NOT NULL,
    LAST_USED_DATE      DATE,
    CONSTRAINT PK_TM_NUM_MANAGER_PASSKEY PRIMARY KEY (CREDENTIAL_ID),
    CONSTRAINT CK_TM_NUM_MANAGER_PASSKEY_USE CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX IX_TM_NUM_MANAGER_PASSKEY_01
    ON TM_NUM_MANAGER_PASSKEY (MANAGER_TEL_HASH, USE_YN);

CREATE INDEX IX_TM_NUM_MANAGER_PASSKEY_02
    ON TM_NUM_MANAGER_PASSKEY (USER_HANDLE, USE_YN);

COMMENT ON TABLE TM_NUM_MANAGER_PASSKEY IS '번호판 매니저 WebAuthn 패스키 공개키';
COMMENT ON COLUMN TM_NUM_MANAGER_PASSKEY.MANAGER_TEL_HASH IS '정규화 휴대폰 번호 SHA-256';
COMMENT ON COLUMN TM_NUM_MANAGER_PASSKEY.PUBLIC_KEY_COSE IS 'Base64URL COSE 공개키';
